# Generated by Django 4.2.4 on 2023-10-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventspage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='email',
        ),
    ]
