# Generated by Django 4.2.4 on 2023-10-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspage', '0002_rename_lastname_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='session',
            field=models.CharField(default='Session n/a', max_length=255),
        ),
    ]
